FPS = 60
SCREEN_WIDTH = 1800
SCREEN_HEIGHT = 900

BOUNCE_LOSS = 0.5
HITSTUN_CONSTANT = 5
HITPAUSE_CONSTANT = 0.1

SPRITE_SIZE = (32, 32)
SCALE_SPRITES = 3  # how much to scale up sprites

INPUT_BUFFER = 6
