MAZES = [
    (
        [
            "...WWWWWWWWWWWWW",
            "......W.....W..W",
            "WWWW..W..W..W..W",
            "W........W.....W",
            "W..WWWW..WWWWWWW",
            "W.....W........W",
            "W..WWWWWWW..WWWW",
            "W..W.....W.....W",
            "W..WWWW..WWWWWWW",
            "W...............",
            "WWWWWWWWWWWWW...",
        ],
        True,
    ),
    (["."], True),
    (
        [
            ".WWWW",
            ".W...",
            ".W.W.",
            ".W.W.",
            "...W.",
        ],
        True,
    ),
    (
        [
            "....WWWW............WWWW............WWWW............",
            "....WWWW............WWWW............WWWW............",
            "....WWWW....WWWW....WWWW....WWWW....WWWW....WWWW....",
            "....WWWW....WWWW....WWWW....WWWW....WWWW....WWWW....",
            "....WWWW....WWWW....WWWW....WWWW....WWWW....WWWW....",
            "....WWWW....WWWW....WWWW....WWWW....WWWW....WWWW....",
            "....WWWW....WWWW....WWWW....WWWW....WWWW....WWWW....",
            "....WWWW....WWWW....WWWW....WWWW....WWWW....WWWW....",
            "....WWWW....WWWW....WWWW....WWWW....WWWW....WWWW....",
            "....WWWW....WWWW....WWWW....WWWW....WWWW....WWWW....",
            "....WWWW....WWWW....WWWW....WWWW....WWWW....WWWW....",
            "....WWWW....WWWW....WWWW....WWWW....WWWW....WWWW....",
            "....WWWW....WWWW....WWWW....WWWW....WWWW....WWWW....",
            "....WWWW....WWWW....WWWW....WWWW....WWWW....WWWW....",
            "....WWWW....WWWW....WWWW....WWWW....WWWW....WWWW....",
            "............WWWW............WWWW............WWWW....",
            "............WWWW............WWWW............WWWW....",
        ],
        True,
    ),
    (
        [
            ".W...........",
            ".WWWWWWWWW.W.",
            ".W.........W.",
            ".W.WWWWWWWWW.",
            ".W...W.....W.",
            ".WWW.WWW.W.W.",
            ".W...W...W.W.",
            ".W.WWW.WWWWW.",
            "...W...W.....",
            "WWWW.WWW.WWWW",
            "...W...W...W.",
            ".W.W.W.WWW.W.",
            ".W...W.......",
        ],
        True,
    ),
    (
        [
            ".W...........",
            ".WWWWWWWWW.W.",
            ".W.........W.",
            ".W.WWWWWWWWW.",
            ".W...W.....W.",
            ".WWW.WWW.W.W.",
            ".W...W...W.W.",
            ".W.WWW.WWWWW.",
            "...W...W.....",
            "WWWW.WWW.WWWW",
            "...W...W...W.",
            ".W.W.W.WWW.W.",
            ".W...W......W",
        ],
        False,
    ),
    (
        [
            "............W",
            ".WWWWWWWWWW.W",
            ".WWWWWWWWWW.W",
            ".WWWWWWWWWW.W",
            ".WWWWWWWWWW.W",
            "............W",
            "WWWWWWWWWWWWW",
        ],
        False,
    ),
    (
        [
            "....................................",
            "....................................",
            "....................................",
            "....................................",
            "....................................",
            "....................................",
            "....................................",
            "....................................",
            "....................................",
            "....................................",
            "....................................",
            "....................................",
            "....................................",
            "....................................",
            "....................................",
            "....................................",
        ],
        True,
    ),
    (
        [
            "   WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
            "   W           W                 W           W",
            "W  WWWW  WWWW  WWWW  W  WWWW  WWWW  W  W  W  W",
            "W     W  W        W  W  W        W  W  W  W  W",
            "WWWW  WWWWWWWWWW  WWWWWWW  WWWWWWWWWWWWWWWW  W",
            "W        W  W  W     W        W  W  W  W     W",
            "WWWW  WWWW  W  WWWW  W  WWWWWWW  W  W  WWWW  W",
            "W  W  W     W           W              W  W  W",
            "W  W  W  WWWWWWWWWW  W  WWWWWWWWWWWWW  W  W  W",
            "W  W  W              W  W                    W",
            "W  W  W  W  WWWW  WWWW  W  WWWWWWWWWWWWWWWW  W",
            "W     W  W  W     W  W  W     W     W        W",
            "W  W  WWWW  WWWWWWW  W  WWWW  W  W  WWWWWWW  W",
            "W  W        W     W  W           W        W  W",
            "WWWWWWW  W  W  W  W  WWWWWWW  WWWWWWWWWWWWW  W",
            "W     W  W     W  W  W  W     W     W        W",
            "WWWW  WWWWWWW  WWWW  W  W  W  WWWW  WWWWWWW  W",
            "W  W        W  W  W  W  W  W     W     W     W",
            "W  W  W  WWWW  W  W  W  WWWW  WWWW  W  WWWW  W",
            "W  W  W  W     W  W     W  W  W     W        W",
            "W  W  WWWWWWW  W  WWWW  W  WWWWWWWWWW  WWWWWWW",
            "W     W     W  W     W        W           W  W",
            "WWWW  W  W  W  W  W  W  WWWW  W  WWWWWWW  W  W",
            "W        W     W  W  W  W           W        W",
            "WWWWWWWWWWWWW  W  W  WWWW  W  WWWWWWW  W  WWWW",
            "W  W        W     W     W  W     W     W     W",
            "W  W  WWWW  WWWW  W  WWWW  W  WWWWWWWWWWWWW  W",
            "W        W     W  W  W     W  W        W  W  W",
            "W  W  WWWW  W  W  WWWW  W  WWWWWWWWWW  W  W  W",
            "W  W     W  W     W     W           W         ",
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW   ",
        ],
        True,
    ),
    (
        [
            "   WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
            "      W     W        W  W  W  W        W        W  W  W        W  W  W     W",
            "WWWW  WWWW  W  WWWWWWW  W  W  W  WWWW  WWWW  WWWW  W  W  W  WWWW  W  W  W  W",
            "W     W        W     W        W  W     W        W     W  W  W     W     W  W",
            "W  WWWW  WWWWWWWWWW  W  W  W  W  WWWW  W  WWWW  W  WWWWWWW  W  WWWW  W  W  W",
            "W  W        W     W     W  W        W  W     W  W  W                 W  W  W",
            "W  WWWW  WWWW  W  WWWWWWWWWWWWWWWW  WWWW  W  WWWW  WWWWWWWWWWWWWWWW  WWWW  W",
            "W     W     W  W           W     W        W           W              W  W  W",
            "W  W  W  WWWW  WWWW  W  W  W  WWWWWWWWWW  WWWWWWW  WWWW  WWWWWWW  WWWW  WWWW",
            "W  W           W  W  W  W  W                    W     W  W                 W",
            "W  WWWW  WWWWWWW  WWWWWWWWWWWWW  W  W  WWWW  W  WWWW  WWWW  WWWWWWW  WWWWWWW",
            "W     W  W              W        W  W  W     W  W     W        W           W",
            "W  WWWW  WWWW  W  WWWWWWW  WWWWWWW  W  WWWW  W  WWWW  WWWWWWW  W  WWWWWWWWWW",
            "W     W  W     W  W     W        W  W  W  W  W  W     W  W     W           W",
            "WWWW  W  WWWW  WWWWWWW  WWWWWWWWWW  WWWW  W  W  WWWW  W  WWWWWWW  W  WWWWWWW",
            "W  W  W        W     W  W  W     W     W     W  W  W     W  W     W  W  W  W",
            "W  WWWW  WWWW  WWWW  W  W  W  WWWWWWWWWWWWW  WWWW  W  WWWW  WWWW  W  W  W  W",
            "W  W     W  W  W           W     W     W     W     W     W  W  W  W  W     W",
            "W  WWWW  W  WWWWWWW  WWWWWWWWWW  WWWW  WWWW  W  W  W  WWWW  W  WWWW  W  WWWW",
            "W           W     W  W     W  W  W           W  W                          W",
            "WWWW  WWWWWWW  W  W  W  WWWW  W  WWWWWWW  WWWW  WWWWWWW  W  WWWWWWWWWWWWW  W",
            "W           W  W     W     W                 W  W  W     W  W  W           W",
            "WWWWWWW  WWWW  W  WWWW  W  W  WWWW  W  WWWW  WWWW  WWWW  WWWW  WWWW  W  WWWW",
            "W              W     W  W     W     W     W  W     W     W        W  W     W",
            "W  WWWW  WWWW  W  WWWW  WWWWWWW  W  WWWW  WWWW  WWWW  WWWW  WWWW  WWWWWWWWWW",
            "W  W  W  W  W  W              W  W  W     W           W     W  W           W",
            "WWWW  W  W  WWWWWWW  WWWWWWW  W  W  WWWWWWW  WWWWWWW  W  W  W  W  WWWW  WWWW",
            "W                 W     W     W  W     W     W  W        W  W        W  W  W",
            "WWWWWWWWWW  WWWWWWWWWW  W  W  WWWW  W  WWWWWWW  WWWW  WWWWWWW  WWWWWWWWWW  W",
            "W  W              W     W  W     W  W              W        W     W        W",
            "W  WWWWWWW  WWWWWWW  WWWWWWW  WWWW  WWWWWWW  WWWWWWWWWWWWWWWW  WWWW  WWWWWWW",
            "W  W     W        W  W     W     W  W                 W     W           W  W",
            "W  WWWW  WWWW  W  WWWW  WWWWWWWWWW  W  WWWW  WWWW  WWWWWWW  W  WWWW  W  W  W",
            "W     W        W        W  W        W  W     W     W     W     W     W  W  W",
            "W  WWWW  WWWWWWW  WWWW  W  WWWWWWWWWW  WWWW  W  WWWW  WWWWWWWWWWWWW  WWWW  W",
            "W     W  W           W        W     W  W  W  W  W        W  W  W           W",
            "W  W  WWWWWWWWWW  WWWW  W  WWWW  WWWWWWW  WWWWWWW  W  W  W  W  W  WWWWWWWWWW",
            "W  W              W     W           W     W  W     W  W        W  W  W  W  W",
            "WWWW  W  WWWW  WWWWWWWWWW  W  W  WWWWWWW  W  W  WWWW  W  W  WWWW  W  W  W  W",
            "W     W  W     W  W  W  W  W  W  W     W     W     W  W  W     W     W     W",
            "WWWWWWW  WWWW  W  W  W  WWWWWWWWWWWWW  W  W  WWWW  WWWW  WWWWWWW  W  W  W  W",
            "W        W        W     W              W  W           W     W     W  W  W  W",
            "W  W  WWWW  WWWWWWWWWW  WWWWWWW  WWWW  WWWW  W  WWWWWWW  WWWWWWW  WWWW  W  W",
            "W  W     W     W           W     W     W  W  W  W           W        W  W  W",
            "W  W  WWWW  WWWWWWW  WWWWWWW  WWWWWWW  W  WWWWWWWWWW  W  WWWW  WWWWWWWWWW  W",
            "W  W  W  W        W  W              W  W  W  W     W  W        W        W  W",
            "WWWW  W  WWWW  W  W  WWWWWWWWWW  W  WWWW  W  W  WWWWWWWWWWWWW  WWWW  WWWW  W",
            "W     W  W  W  W     W     W     W  W  W  W        W  W  W        W  W  W  W",
            "WWWW  W  W  WWWW  W  W  WWWW  WWWWWWW  W  WWWW  W  W  W  WWWW  WWWW  W  W  W",
            "W           W     W                       W     W                           ",
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW   ",
        ],
        True,
    ),
    (
        [
            "   WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
            "            W                             W        W           W        W  W              W",
            "W  WWWWWWWWWWWWWWWWWWW  WWWWWWW  W  WWWWWWWWWWWWW  W  W  W  W  WWWW  W  W  WWWW  WWWWWWWWWW",
            "W  W     W  W              W     W  W        W        W  W  W  W     W     W     W  W  W  W",
            "W  WWWW  W  WWWWWWWWWWWWWWWW  W  W  W  W  WWWWWWWWWWWWW  WWWW  W  WWWW  WWWW  W  W  W  W  W",
            "W                 W        W  W  W  W  W     W        W  W     W  W           W  W        W",
            "W  WWWWWWWWWW  WWWWWWWWWW  W  W  WWWW  W  W  W  WWWW  W  W  WWWW  W  WWWWWWWWWW  W  WWWW  W",
            "W           W     W  W  W  W  W     W  W  W     W  W     W     W  W        W  W     W     W",
            "WWWWWWWWWW  WWWWWWW  W  W  WWWWWWW  W  WWWW  WWWW  WWWW  W  WWWWWWW  WWWW  W  W  WWWWWWWWWW",
            "W     W              W     W              W     W        W  W        W  W  W     W  W  W  W",
            "WWWW  WWWWWWWWWW  WWWW  W  WWWW  WWWWWWWWWWWWW  W  W  WWWWWWWWWW  WWWW  WWWW  WWWW  W  W  W",
            "W     W  W              W           W        W  W  W        W        W  W        W        W",
            "W  W  W  W  W  W  WWWWWWWWWWWWW  WWWW  WWWW  WWWW  W  W  WWWWWWWWWW  W  W  WWWWWWWWWW  WWWW",
            "W  W     W  W  W  W  W     W  W     W     W     W  W  W  W     W     W     W     W     W  W",
            "WWWWWWW  W  W  WWWW  W  W  W  WWWW  WWWW  WWWWWWWWWW  WWWW  WWWW  WWWWWWWWWWWWW  W  W  W  W",
            "W           W        W  W     W                    W           W  W           W     W  W  W",
            "WWWW  WWWWWWWWWW  WWWWWWW  WWWW  W  WWWW  W  W  WWWWWWW  WWWWWWW  W  WWWWWWW  WWWW  WWWW  W",
            "W  W        W        W  W     W  W  W     W  W  W  W                 W  W     W           W",
            "W  WWWW  WWWWWWW  W  W  WWWW  W  WWWWWWW  WWWWWWW  WWWWWWW  WWWW  W  W  WWWW  W  WWWWWWW  W",
            "W  W     W     W  W  W        W  W        W              W  W  W  W  W     W     W     W  W",
            "W  W  WWWW  WWWWWWWWWWWWWWWW  W  W  WWWWWWWWWW  W  WWWW  W  W  WWWW  WWWW  W  WWWWWWW  W  W",
            "W              W  W              W  W  W     W  W  W        W  W  W        W     W        W",
            "WWWW  WWWW  WWWW  W  WWWWWWW  W  WWWW  W  WWWW  WWWW  WWWW  W  W  W  W  WWWW  WWWWWWWWWW  W",
            "W        W     W  W     W  W  W        W     W  W     W  W  W        W  W  W        W     W",
            "WWWWWWW  WWWWWWW  W  WWWW  WWWWWWWWWWWWWWWW  WWWWWWWWWW  W  WWWW  WWWWWWW  WWWWWWW  W  W  W",
            "W  W     W           W  W        W        W     W  W     W     W              W     W  W  W",
            "W  WWWWWWWWWW  W  WWWW  W  W  WWWWWWWWWW  WWWW  W  WWWW  W  WWWW  WWWWWWWWWWWWW  WWWW  WWWW",
            "W           W  W           W     W                 W           W        W  W     W     W  W",
            "WWWW  WWWWWWWWWWWWW  WWWWWWW  WWWW  WWWWWWW  WWWWWWW  WWWW  WWWWWWW  WWWW  WWWWWWWWWW  W  W",
            "W           W           W        W  W  W        W     W        W  W  W     W        W     W",
            "W  W  WWWWWWW  W  W  WWWWWWW  WWWWWWW  W  WWWWWWW  WWWWWWWWWWWWW  WWWW  WWWWWWW  WWWWWWW  W",
            "W  W     W     W  W        W     W     W           W                    W        W        W",
            "W  WWWWWWW  WWWW  WWWW  WWWWWWW  WWWW  W  WWWWWWW  WWWWWWW  WWWW  WWWW  WWWW  WWWW  WWWWWWW",
            "W        W  W  W     W  W     W        W        W     W     W  W  W  W  W                 W",
            "W  W  W  WWWW  WWWWWWW  WWWW  WWWW  WWWW  WWWW  WWWWWWWWWWWWW  W  W  WWWWWWW  W  W  W  W  W",
            "W  W  W  W           W  W  W     W  W     W           W           W     W     W  W  W  W  W",
            "W  WWWWWWWWWWWWW  WWWWWWW  W  W  WWWWWWWWWWWWW  W  W  W  W  W  WWWWWWW  W  WWWW  WWWWWWWWWW",
            "W  W     W  W              W  W     W     W     W  W  W  W  W     W     W  W        W  W  W",
            "W  W  WWWW  WWWWWWW  WWWW  WWWWWWW  W  WWWW  WWWWWWW  W  W  W  W  WWWW  WWWWWWW  W  W  W  W",
            "W     W     W        W  W        W                 W  W  W  W  W  W              W        W",
            "W  WWWW  WWWW  W  W  W  W  WWWWWWWWWW  WWWWWWW  W  W  WWWW  W  W  W  W  WWWWWWW  WWWW  WWWW",
            "W     W        W  W  W        W        W  W     W  W  W     W  W     W  W  W        W  W  W",
            "WWWW  W  W  W  W  WWWWWWW  W  W  W  W  W  WWWWWWWWWWWWW  WWWW  WWWW  W  W  WWWWWWW  WWWW  W",
            "W     W  W  W  W     W     W     W  W  W  W        W     W  W     W  W     W     W     W  W",
            "W  WWWW  WWWW  W  W  WWWWWWWWWWWWW  W  W  WWWW  WWWWWWW  W  WWWWWWW  W  W  W  W  W  W  W  W",
            "W        W  W  W  W        W  W  W  W  W              W  W  W     W  W  W     W  W  W     W",
            "W  WWWWWWW  WWWWWWWWWWWWW  W  W  WWWW  WWWW  WWWW  WWWW  W  W  WWWWWWWWWW  WWWWWWW  WWWWWWW",
            "W           W     W              W     W     W        W  W        W  W     W           W  W",
            "WWWW  W  W  WWWW  W  W  WWWW  W  WWWW  W  WWWWWWW  WWWWWWW  W  WWWW  W  W  W  W  WWWWWWW  W",
            "W  W  W  W  W  W  W  W     W  W     W  W     W  W        W  W           W  W  W  W  W     W",
            "W  W  WWWWWWW  W  WWWW  WWWW  WWWWWWW  WWWW  W  WWWWWWW  W  WWWW  WWWWWWWWWW  W  W  W  WWWW",
            "W        W        W     W  W  W              W  W  W  W  W     W        W     W  W     W  W",
            "WWWWWWWWWWWWW  WWWW  W  W  WWWWWWWWWWWWW  WWWW  W  W  WWWWWWW  WWWWWWWWWWWWWWWW  WWWW  W  W",
            "W  W  W     W        W     W  W  W  W        W        W     W        W                 W  W",
            "W  W  WWWW  WWWWWWW  W  WWWW  W  W  WWWWWWW  WWWWWWW  W  WWWWWWW  WWWWWWWWWWWWWWWWWWWWWW  W",
            "W     W     W  W     W  W        W  W        W  W           W  W     W                 W  W",
            "W  WWWW  WWWW  W  WWWWWWW  WWWWWWW  WWWWWWWWWW  WWWW  WWWW  W  WWWWWWWWWWWWWWWW  W  WWWW  W",
            "W  W                    W           W     W        W  W  W     W        W     W  W  W     W",
            "W  W  W  WWWWWWW  WWWWWWW  WWWWWWWWWWWWW  W  WWWWWWW  W  WWWWWWWWWW  WWWW  WWWWWWW  W  WWWW",
            "W     W        W              W  W        W     W              W     W                    W",
            "W  WWWWWWW  WWWWWWWWWWWWWWWW  W  W  WWWWWWW  W  WWWWWWW  W  WWWWWWW  WWWW  WWWW  WWWW  WWWW",
            "W     W        W              W  W           W        W  W           W     W        W     W",
            "WWWWWWWWWWWWWWWWWWWWWW  WWWW  W  W  WWWW  W  W  WWWW  WWWW  WWWWWWW  WWWW  WWWW  WWWW  W  W",
            "W  W              W     W              W  W  W  W        W  W  W           W  W     W  W  W",
            "W  WWWW  W  WWWW  WWWW  WWWWWWWWWWWWW  WWWWWWWWWWWWWWWW  W  W  WWWWWWW  WWWW  W  WWWWWWW  W",
            "W  W     W  W     W  W  W  W     W           W  W     W        W  W        W     W        W",
            "W  WWWW  W  W  W  W  W  W  W  W  W  WWWWWWWWWW  W  WWWW  WWWW  W  W  WWWW  W  W  W  WWWWWWW",
            "W     W  W  W  W  W  W        W  W     W        W           W     W  W     W  W  W  W     W",
            "W  WWWWWWW  WWWW  W  W  WWWW  W  WWWWWWWWWWWWW  W  W  W  W  WWWWWWW  W  WWWW  W  W  WWWW  W",
            "W  W        W              W  W        W        W  W  W  W     W  W  W  W  W  W  W        W",
            "W  W  WWWWWWW  W  W  W  WWWWWWW  WWWWWWWWWW  WWWWWWW  WWWWWWW  W  WWWWWWW  WWWWWWWWWWWWW  W",
            "W     W  W     W  W  W  W  W  W  W  W  W     W     W     W                             W  W",
            "W  WWWW  W  W  WWWW  W  W  W  WWWW  W  W  W  WWWW  W  WWWWWWWWWWWWWWWW  WWWWWWW  WWWWWWW  W",
            "W     W     W  W     W  W  W  W  W        W  W  W        W           W  W  W        W  W  W",
            "W  W  WWWW  W  W  WWWW  W  W  W  WWWW  WWWWWWW  W  WWWW  W  WWWW  WWWWWWW  W  WWWW  W  W  W",
            "W  W     W  W  W     W     W                    W     W     W        W     W     W     W  W",
            "WWWWWWW  WWWWWWW  WWWW  WWWWWWW  WWWWWWWWWWWWWWWW  WWWW  WWWWWWW  WWWW  W  W  WWWW  WWWW  W",
            "W  W     W  W  W  W        W        W     W  W     W  W  W  W  W        W  W  W     W     W",
            "W  W  WWWW  W  W  W  WWWW  W  WWWWWWWWWW  W  WWWWWWW  W  W  W  WWWW  WWWW  W  WWWW  WWWW  W",
            "W     W           W     W                       W                 W     W  W  W     W      ",
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW   ",
        ],
        True,
    ),
    (
        [
            "   WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
            "               W                    W     W     W     W                 W  W     W  W  W                             W        W        W              W",
            "W  WWWWWWWWWW  W  W  WWWWWWWWWW  W  W  W  W  WWWW  W  WWWWWWW  WWWWWWW  W  WWWW  W  W  W  WWWWWWW  WWWWWWW  W  W  W  WWWW  W  W  W  WWWW  WWWWWWWWWWWWW",
            "W  W     W        W     W        W  W  W        W  W  W  W     W     W     W        W     W        W  W     W  W  W        W     W              W     W",
            "W  WWWW  WWWW  WWWWWWWWWWWWW  WWWW  W  WWWWWWWWWWWWW  W  WWWW  WWWW  WWWW  W  WWWW  W  WWWW  WWWWWWW  WWWW  WWWWWWW  W  WWWW  WWWWWWWWWW  WWWWWWWWWW  W",
            "W  W                    W  W  W           W  W        W              W           W  W     W        W     W  W        W  W           W              W  W",
            "WWWWWWW  W  WWWWWWW  WWWW  WWWWWWWWWW  W  W  WWWW  WWWWWWWWWW  WWWWWWWWWWWWW  WWWW  W  W  WWWWWWWWWWWWW  WWWWWWWWWWWWW  WWWW  W  WWWWWWW  WWWWWWWWWW  W",
            "W  W     W  W           W     W  W  W  W  W  W        W        W              W     W  W  W  W  W  W     W     W        W     W        W  W        W  W",
            "W  WWWWWWWWWWWWWWWW  WWWW  W  W  W  W  WWWW  WWWW  WWWWWWWWWW  WWWWWWW  WWWWWWWWWWWWWWWW  W  W  W  W  WWWWWWW  WWWWWWW  WWWW  WWWWWWWWWW  WWWWWWW  W  W",
            "W        W        W  W     W        W  W     W        W           W           W        W     W        W  W     W     W  W        W  W              W  W",
            "WWWWWWW  WWWWWWW  W  WWWW  WWWW  WWWW  WWWW  W  W  WWWWWWW  WWWW  W  WWWW  W  W  WWWW  W  WWWWWWW  WWWW  WWWW  W  W  W  WWWW  WWWW  WWWWWWW  W  WWWW  W",
            "W  W           W              W  W        W     W           W  W  W  W     W  W  W           W        W     W     W        W  W  W     W     W  W     W",
            "W  W  WWWWWWW  W  WWWW  WWWWWWWWWW  W  WWWW  WWWWWWWWWWWWWWWW  W  WWWWWWWWWWWWW  WWWW  WWWW  W  W  WWWW  W  WWWW  WWWW  W  W  W  WWWW  W  W  WWWW  W  W",
            "W        W        W  W     W        W  W        W           W     W     W     W  W  W  W  W     W  W     W     W  W     W  W  W  W        W        W  W",
            "W  WWWWWWW  WWWWWWW  W  W  WWWWWWWWWW  WWWWWWW  WWWW  WWWWWWWWWWWWW  W  WWWW  WWWW  WWWW  WWWW  W  W  W  WWWWWWWWWWWWWWWWWWW  W  W  WWWWWWWWWW  WWWWWWW",
            "W     W  W  W     W     W  W     W           W     W        W  W     W  W  W              W     W     W        W     W        W           W     W  W  W",
            "WWWWWWW  W  W  WWWWWWWWWWWWW  WWWW  WWWW  WWWWWWW  WWWWWWW  W  W  WWWW  W  WWWWWWW  WWWW  WWWWWWW  W  WWWW  WWWW  WWWW  W  WWWWWWW  WWWWWWWWWWWWW  W  W",
            "W                 W              W     W  W        W        W  W  W        W        W  W  W     W  W     W     W  W     W        W  W        W  W     W",
            "W  W  WWWW  WWWW  WWWW  WWWWWWWWWW  W  WWWW  WWWWWWWWWW  WWWW  WWWW  WWWW  WWWWWWW  W  WWWW  W  WWWWWWWWWW  WWWW  WWWW  WWWW  WWWW  WWWWWWW  W  W  W  W",
            "W  W  W     W     W     W  W        W  W  W           W  W     W     W     W  W              W     W  W     W  W  W  W  W  W     W     W  W        W  W",
            "WWWW  WWWWWWWWWW  WWWW  W  WWWWWWW  W  W  W  WWWW  WWWW  W  WWWWWWWWWW  WWWW  WWWW  WWWWWWW  W  WWWW  W  WWWW  W  W  WWWW  WWWWWWWWWW  W  W  WWWW  W  W",
            "W  W  W           W                 W        W  W     W                       W  W  W        W     W     W  W  W              W  W  W  W        W  W  W",
            "W  WWWW  WWWWWWW  W  WWWWWWWWWWWWW  W  WWWWWWW  WWWWWWWWWW  W  WWWW  WWWW  W  W  W  WWWW  W  WWWW  W  W  W  W  W  WWWWWWW  WWWW  W  WWWW  W  W  WWWW  W",
            "W              W  W  W     W  W  W  W     W  W     W     W  W     W  W     W     W     W  W  W     W  W                 W        W        W  W     W  W",
            "W  W  WWWWWWWWWW  WWWW  W  W  W  W  W  W  W  W  WWWW  W  W  WWWWWWWWWWWWW  W  W  WWWWWWW  WWWW  WWWW  WWWW  WWWW  WWWW  WWWWWWW  W  WWWW  W  WWWW  W  W",
            "W  W  W  W  W           W     W     W  W     W  W  W  W  W        W        W  W  W     W     W        W        W     W  W  W  W  W  W     W  W     W  W",
            "W  WWWW  W  WWWW  WWWW  WWWW  WWWWWWW  WWWW  W  W  WWWW  W  W  W  WWWW  W  W  W  WWWW  WWWWWWWWWW  WWWW  WWWWWWW  W  W  W  W  W  WWWWWWW  W  W  WWWW  W",
            "W        W           W     W     W        W  W     W     W  W  W     W  W  W  W  W        W     W     W  W     W  W  W     W  W           W  W     W  W",
            "WWWWWWWWWWWWW  WWWW  WWWW  WWWW  W  W  WWWWWWW  WWWWWWW  W  WWWWWWWWWW  WWWW  WWWWWWWWWW  WWWW  W  WWWW  WWWW  WWWWWWW  WWWW  W  WWWWWWWWWWWWWWWWWWWWWW",
            "W     W        W  W  W        W  W  W  W        W           W     W  W     W        W                 W  W        W        W     W     W     W  W     W",
            "W  WWWW  W  WWWW  WWWW  WWWWWWW  W  WWWW  W  WWWWWWWWWWWWW  W  WWWW  WWWWWWWWWWWWW  WWWW  WWWW  W  W  WWWW  W  W  W  WWWWWWWWWWWWW  WWWW  W  W  WWWW  W",
            "W  W     W  W  W  W        W     W  W     W     W  W        W           W           W     W     W  W  W     W  W  W              W     W  W        W  W",
            "W  WWWWWWWWWW  W  WWWWWWW  W  WWWW  WWWWWWW  WWWW  WWWWWWW  W  W  WWWWWWW  WWWWWWW  WWWW  W  WWWW  WWWW  WWWWWWWWWWWWW  W  W  WWWWWWW  WWWW  WWWW  W  W",
            "W           W  W           W  W  W     W  W  W              W  W        W  W     W        W  W  W        W     W  W  W  W  W              W     W  W  W",
            "W  WWWW  WWWW  W  WWWWWWWWWW  W  WWWWWWW  W  W  W  WWWW  W  W  WWWW  WWWW  WWWW  WWWW  WWWW  W  WWWW  WWWW  W  W  W  W  WWWW  WWWWWWW  WWWWWWW  W  W  W",
            "W     W     W  W  W     W              W        W  W  W  W  W  W        W  W  W  W  W     W        W  W     W     W     W     W     W        W  W     W",
            "WWWWWWW  WWWW  W  WWWW  W  WWWW  W  WWWWWWWWWWWWWWWW  WWWWWWW  WWWWWWW  WWWW  W  W  WWWW  WWWW  WWWW  WWWWWWW  WWWW  WWWWWWW  W  WWWWWWWWWW  W  W  WWWW",
            "W        W  W        W  W  W     W                 W     W  W     W     W  W  W     W     W        W     W        W     W              W        W  W  W",
            "WWWW  W  W  WWWWWWWWWW  W  WWWWWWW  WWWWWWW  WWWW  W  W  W  W  WWWWWWW  W  W  W  WWWW  W  W  WWWWWWW  WWWWWWWWWW  W  WWWW  W  W  W  W  W  WWWW  WWWW  W",
            "W     W        W  W     W  W  W     W     W  W  W  W  W           W  W           W  W  W  W     W  W        W           W  W  W  W  W  W  W     W  W  W",
            "WWWW  W  WWWWWWW  WWWW  W  W  WWWWWWWWWW  WWWW  W  WWWWWWW  WWWW  W  W  WWWWWWW  W  W  W  WWWWWWW  W  WWWWWWWWWWWWW  W  WWWWWWWWWWWWWWWWWWWWWW  W  W  W",
            "W     W  W        W  W  W  W  W     W     W     W     W     W  W  W           W  W     W     W              W     W  W     W     W     W  W     W     W",
            "WWWW  W  WWWWWWW  W  W  W  W  W  WWWWWWW  W  WWWW  WWWWWWW  W  W  W  WWWWWWW  W  WWWW  WWWWWWW  W  W  WWWW  WWWW  WWWWWWW  WWWW  W  W  W  WWWW  WWWW  W",
            "W     W     W  W        W  W  W     W        W     W        W     W     W  W  W              W  W  W     W  W           W        W  W  W     W  W  W  W",
            "WWWWWWWWWW  W  W  W  W  W  W  W  W  W  WWWW  W  W  W  WWWWWWWWWWWWWWWW  W  WWWW  WWWW  W  WWWWWWWWWW  WWWWWWWWWW  WWWWWWWWWWWWW  W  WWWW  WWWWWWW  W  W",
            "W  W              W  W        W  W  W  W  W  W  W              W  W     W  W        W  W     W     W        W  W        W  W  W  W  W           W     W",
            "W  W  W  W  WWWWWWWWWWWWW  WWWWWWW  W  W  WWWW  WWWW  W  W  WWWW  WWWWWWW  WWWW  W  WWWWWWW  WWWW  W  WWWW  W  W  W  WWWW  W  W  W  WWWWWWWWWW  W  W  W",
            "W     W  W        W     W     W     W           W  W  W  W  W     W  W           W  W  W  W     W  W  W  W     W  W     W  W        W  W           W  W",
            "WWWW  W  W  W  WWWW  WWWW  W  WWWW  WWWW  WWWWWWW  W  WWWWWWWWWW  W  WWWWWWW  WWWW  W  W  WWWWWWW  WWWW  W  W  W  WWWWWWW  W  WWWW  W  W  W  WWWWWWWWWW",
            "W     W  W  W  W        W  W        W        W  W  W  W           W  W     W  W  W     W              W     W     W  W        W           W        W  W",
            "WWWW  WWWWWWWWWW  WWWWWWWWWW  WWWWWWWWWW  WWWW  W  WWWWWWWWWWWWW  W  W  W  W  W  WWWWWWW  W  WWWW  WWWW  W  W  WWWW  WWWW  WWWWWWWWWWWWWWWW  W  WWWW  W",
            "W                    W  W        W     W     W     W        W  W        W  W  W  W     W  W  W        W  W  W        W  W        W  W     W  W  W     W",
            "WWWW  WWWWWWW  WWWWWWW  W  WWWWWWW  WWWWWWWWWWWWW  W  W  WWWW  W  WWWWWWW  W  W  WWWW  WWWWWWWWWWWWW  WWWWWWW  W  W  W  W  WWWW  W  WWWW  W  W  W  WWWW",
            "W           W           W     W              W        W  W  W     W           W  W     W     W     W  W  W  W  W  W  W        W  W  W        W        W",
            "W  W  WWWWWWW  W  WWWWWWWWWWWWWWWWWWW  W  WWWW  WWWWWWWWWW  W  W  WWWWWWWWWW  W  WWWW  WWWW  W  WWWW  W  W  WWWWWWW  W  W  W  WWWW  WWWW  WWWWWWW  WWWW",
            "W  W  W  W     W        W     W  W  W  W  W  W     W           W  W                 W                 W     W        W  W  W  W     W           W     W",
            "WWWWWWW  W  WWWW  W  W  WWWW  W  W  W  WWWW  WWWW  W  W  WWWWWWW  W  WWWW  WWWWWWW  W  WWWW  W  WWWWWWWWWW  WWWW  WWWW  WWWWWWWWWW  W  WWWWWWW  W  WWWW",
            "W  W  W  W     W  W  W              W     W  W     W  W        W  W  W  W  W        W  W     W        W  W  W  W     W  W  W  W  W     W        W     W",
            "W  W  W  WWWWWWW  W  W  WWWW  W  W  W  WWWW  WWWW  WWWW  WWWW  WWWW  W  W  WWWWWWWWWWWWWWWWWWWWWWWWW  W  W  W  WWWW  WWWW  W  W  WWWWWWWWWW  WWWWWWW  W",
            "W     W     W     W  W  W     W  W     W     W              W     W     W     W     W                    W  W  W  W     W  W                    W     W",
            "WWWW  W  W  W  WWWW  W  WWWW  WWWW  W  WWWW  WWWW  WWWWWWWWWW  W  WWWWWWW  W  W  W  W  W  W  WWWWWWW  W  W  W  W  W  WWWW  W  WWWWWWWWWW  W  W  WWWWWWW",
            "W  W     W  W  W  W  W     W  W  W  W  W              W        W  W     W  W  W  W     W  W  W        W     W  W     W        W        W  W  W  W  W  W",
            "W  WWWW  WWWWWWW  WWWWWWWWWW  W  WWWW  WWWW  WWWWWWW  WWWW  WWWWWWWWWW  WWWWWWWWWW  W  WWWWWWWWWW  WWWWWWW  W  W  WWWWWWW  WWWWWWWWWW  WWWWWWWWWW  W  W",
            "W  W        W                    W     W        W     W  W  W     W     W     W  W  W  W              W  W     W  W     W  W              W           W",
            "W  W  WWWW  WWWW  WWWWWWW  WWWW  W  WWWWWWWWWW  W  W  W  W  WWWW  W  WWWW  WWWW  WWWWWWWWWWWWWWWWWWWWWW  WWWW  WWWW  WWWWWWWWWWWWW  W  W  WWWWWWWWWW  W",
            "W  W  W     W  W  W     W  W     W  W  W     W  W  W     W     W  W                 W     W  W     W           W              W     W  W     W        W",
            "W  WWWWWWW  W  WWWWWWW  W  WWWW  WWWW  W  W  WWWWWWW  W  W  WWWW  WWWWWWWWWWWWW  WWWWWWW  W  W  WWWWWWWWWWWWW  WWWW  WWWWWWW  WWWW  WWWW  WWWWWWW  W  W",
            "W  W     W  W  W  W     W  W        W     W           W  W     W  W              W  W  W  W  W     W  W  W        W  W        W     W     W     W  W  W",
            "W  W  W  W  W  W  WWWW  WWWW  WWWWWWW  W  WWWWWWW  W  WWWW  W  W  WWWW  WWWWWWW  W  W  W  W  WWWW  W  W  WWWW  WWWWWWWWWW  WWWWWWW  WWWWWWWWWW  W  W  W",
            "W     W  W  W     W  W           W  W  W        W  W  W  W  W  W           W  W  W        W     W  W  W     W           W  W        W     W  W     W  W",
            "WWWW  WWWW  WWWW  W  WWWW  WWWW  W  WWWWWWWWWW  W  WWWW  W  WWWWWWWWWW  WWWW  WWWWWWW  WWWWWWW  W  W  WWWW  WWWWWWWWWW  W  WWWWWWW  W  WWWW  W  WWWWWWW",
            "W              W     W     W                 W  W     W  W     W        W  W  W  W        W           W           W              W  W                 W",
            "W  WWWWWWW  WWWW  WWWW  W  WWWW  WWWW  WWWWWWW  W  WWWW  W  WWWW  WWWWWWW  W  W  W  WWWW  WWWWWWW  WWWWWWWWWW  WWWWWWWWWWWWW  W  W  W  WWWWWWWWWWWWWWWW",
            "W     W  W  W           W  W  W  W  W        W  W  W     W                    W  W  W     W     W     W  W  W  W        W  W  W  W  W              W  W",
            "WWWW  W  W  WWWW  WWWWWWWWWW  W  W  W  WWWWWWWWWW  WWWW  W  W  W  WWWW  W  W  W  WWWW  WWWW  WWWW  WWWW  W  W  WWWW  WWWW  WWWW  W  W  WWWWWWWWWWWWW  W",
            "W  W     W  W        W     W        W     W     W  W     W  W  W  W  W  W  W              W        W        W                 W  W  W        W     W  W",
            "W  W  WWWWWWW  WWWW  WWWW  W  WWWW  WWWWWWWWWW  WWWW  WWWW  WWWWWWW  W  WWWWWWWWWW  W  W  W  W  WWWWWWW  WWWWWWWWWW  WWWWWWWWWW  W  W  W  WWWW  WWWW  W",
            "W     W        W           W     W  W     W  W                 W  W     W           W  W     W                 W           W  W        W     W        W",
            "W  WWWW  W  WWWWWWWWWW  WWWWWWW  WWWWWWW  W  W  WWWWWWWWWWWWWWWW  WWWWWWWWWWWWW  WWWWWWWWWWWWWWWWWWWWWWWWWWWW  WWWW  WWWWWWW  W  WWWW  WWWW  W  WWWW  W",
            "W        W        W  W  W     W              W  W  W           W           W  W     W           W        W        W        W        W     W     W  W  W",
            "W  WWWW  WWWWWWW  W  W  W  W  WWWW  WWWW  WWWWWWW  WWWW  W  WWWW  WWWW  WWWW  WWWW  W  W  WWWWWWW  WWWWWWW  WWWW  WWWWWWW  W  WWWW  W  WWWWWWW  W  W  W",
            "W     W        W  W     W  W  W     W  W           W     W     W  W  W           W     W  W  W     W        W  W     W     W  W     W  W  W        W  W",
            "WWWWWWW  WWWWWWW  WWWWWWWWWW  WWWWWWW  W  W  WWWW  WWWW  WWWW  WWWW  WWWWWWWWWW  W  WWWW  W  W  W  WWWWWWW  W  WWWW  W  W  W  WWWW  WWWW  W  WWWWWWWWWW",
            "W     W        W     W     W     W  W     W  W           W        W  W  W           W     W  W  W  W  W  W     W     W  W        W  W     W           W",
            "W  WWWWWWWWWWWWWWWWWWW  W  WWWW  W  W  WWWWWWWWWWWWWWWW  WWWWWWWWWW  W  W  WWWWWWWWWW  WWWW  W  WWWW  W  W  WWWWWWW  W  WWWWWWW  W  WWWW  WWWWWWWWWW  W",
            "W              W        W     W                 W                       W           W  W              W  W  W     W  W        W  W     W           W  W",
            "WWWW  W  WWWWWWWWWWWWW  W  W  WWWW  W  W  WWWWWWWWWW  WWWW  WWWWWWW  W  WWWW  WWWW  WWWWWWWWWWWWWWWW  W  W  W  WWWWWWWWWW  WWWW  WWWW  WWWW  WWWW  WWWW",
            "W  W  W  W     W        W  W  W     W  W  W              W        W  W  W     W        W     W  W     W  W     W        W  W  W  W     W     W        W",
            "W  WWWW  W  W  WWWW  WWWW  WWWW  WWWWWWWWWWWWW  WWWW  WWWWWWW  WWWWWWWWWW  W  W  WWWWWWWWWW  W  W  WWWW  W  W  W  WWWWWWW  W  WWWWWWW  W  WWWWWWWWWW  W",
            "W  W     W  W  W  W  W  W  W  W  W     W        W  W     W           W     W  W  W  W        W              W              W        W  W     W        W",
            "W  W  WWWW  W  W  W  W  WWWW  WWWWWWW  W  W  W  W  WWWW  WWWW  WWWWWWW  W  WWWWWWW  WWWW  WWWWWWWWWW  WWWWWWWWWWWWW  WWWWWWWWWW  WWWWWWW  W  WWWWWWWWWW",
            "W  W     W  W  W     W           W     W  W  W     W     W     W        W                    W     W        W           W     W     W     W  W  W     W",
            "W  W  WWWW  WWWW  WWWW  W  WWWWWWW  W  WWWW  WWWWWWWWWWWWWWWWWWW  W  WWWW  W  W  WWWWWWW  WWWWWWW  W  W  W  WWWW  WWWW  WWWW  W  WWWW  W  W  W  WWWW  W",
            "W     W        W     W  W  W     W  W  W        W  W        W     W  W  W  W  W  W        W     W     W  W     W     W  W              W  W           W",
            "WWWW  W  WWWWWWW  WWWW  W  W  WWWW  WWWW  WWWW  W  W  W  WWWWWWW  W  W  WWWW  WWWWWWWWWWWWWWWW  W  W  WWWWWWWWWWWWW  WWWWWWW  WWWWWWW  WWWW  WWWW  W  W",
            "W  W              W  W  W                 W     W  W  W  W        W  W                          W  W  W           W        W     W  W  W     W  W  W  W",
            "W  WWWW  WWWWWWW  W  W  WWWWWWWWWW  W  W  WWWWWWW  W  W  W  W  W  WWWWWWWWWWWWW  WWWWWWW  WWWWWWW  W  WWWWWWWWWW  W  WWWW  W  WWWW  W  WWWW  W  WWWWWWW",
            "W           W  W           W        W  W        W  W  W     W  W  W  W     W           W        W  W        W        W        W           W  W        W",
            "W  W  WWWWWWW  WWWW  WWWWWWWWWWWWWWWW  W  WWWW  W  W  WWWWWWW  WWWW  W  WWWW  WWWW  WWWW  W  WWWW  WWWWWWWWWW  WWWWWWWWWW  WWWW  W  WWWWWWW  WWWW  WWWW",
            "W  W     W                       W     W     W     W        W        W        W        W  W     W     W              W     W     W        W            ",
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW   ",
        ],
        True,
    ),
    (
        [
            "   WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
            "                  W  W     W  W        W           W     W        W  W     W     W                       W  W  W        W        W     W  W        W  W",
            "W  W  WWWWWWW  WWWW  WWWW  W  W  W  W  WWWW  WWWWWWW  WWWWWWW  WWWW  W  WWWWWWW  W  WWWWWWW  WWWW  WWWWWWW  W  W  W  WWWWWWWWWW  W  WWWW  WWWWWWW  W  W",
            "W  W     W        W     W        W  W        W  W        W        W     W     W        W  W  W  W                 W  W  W        W              W  W  W",
            "WWWWWWW  WWWW  W  W  WWWWWWWWWW  WWWWWWW  W  W  W  WWWWWWWWWW  WWWW  WWWW  WWWW  W  W  W  WWWW  W  WWWW  WWWWWWW  W  W  WWWW  W  W  W  WWWWWWW  W  W  W",
            "W  W  W     W  W        W  W  W        W  W                 W     W        W     W  W        W     W  W  W  W  W  W  W        W     W        W     W  W",
            "W  W  W  WWWWWWWWWW  WWWW  W  W  WWWWWWW  WWWW  WWWW  WWWWWWW  WWWW  WWWWWWW  WWWWWWWWWW  W  WWWW  W  WWWW  W  W  WWWW  W  W  WWWWWWW  WWWWWWW  W  W  W",
            "W        W  W                 W     W        W     W     W                 W  W           W     W     W  W     W  W     W  W        W  W        W     W",
            "W  W  W  W  W  WWWWWWWWWW  WWWW  W  WWWW  WWWWWWW  W  WWWW  WWWW  W  W  WWWWWWW  W  WWWWWWWWWWWWWWWW  W  WWWW  W  WWWW  WWWW  W  WWWWWWWWWW  WWWW  WWWW",
            "W  W  W  W           W  W  W     W  W     W        W           W  W  W           W     W     W     W  W     W              W  W           W  W        W",
            "WWWWWWWWWW  WWWWWWW  W  WWWWWWW  WWWW  WWWWWWW  W  WWWWWWWWWW  WWWWWWW  WWWW  W  WWWW  W  WWWW  WWWWWWW  W  WWWWWWW  WWWW  W  W  WWWWWWWWWWWWWWWW  W  W",
            "W        W     W  W     W  W     W  W  W  W  W  W  W     W  W  W     W     W  W  W  W     W  W  W     W  W     W  W  W     W  W  W     W  W  W     W  W",
            "W  WWWWWWW  W  W  WWWWWWW  WWWWWWW  W  W  W  WWWWWWWWWW  W  W  W  WWWW  WWWW  WWWW  W  W  W  W  W  WWWWWWWWWW  W  W  WWWWWWWWWWWWWWWW  W  W  W  WWWW  W",
            "W     W  W  W        W  W  W  W  W           W  W  W        W  W     W     W     W     W     W        W        W     W        W  W     W           W  W",
            "W  WWWW  WWWWWWWWWW  W  W  W  W  WWWWWWWWWW  W  W  WWWWWWW  W  WWWW  WWWWWWW  WWWWWWWWWWWWWWWW  W  WWWWWWW  WWWW  WWWWWWW  WWWW  WWWW  W  WWWWWWW  WWWW",
            "W           W     W           W  W                    W     W     W        W  W        W        W        W     W                 W     W  W           W",
            "W  WWWW  W  W  WWWWWWW  W  WWWW  W  WWWWWWWWWW  WWWWWWW  W  WWWW  W  W  WWWWWWWWWWWWW  W  WWWW  WWWWWWW  W  W  W  W  WWWWWWWWWWWWWWWW  WWWW  WWWWWWWWWW",
            "W     W  W     W  W     W     W     W        W           W  W     W  W        W  W  W     W           W  W  W     W        W  W        W  W     W     W",
            "WWWWWWWWWWWWW  W  W  WWWW  W  W  WWWW  WWWWWWW  W  WWWW  WWWW  WWWW  WWWW  WWWW  W  W  WWWWWWWWWW  W  W  W  W  WWWWWWW  WWWW  WWWWWWW  W  W  WWWWWWW  W",
            "W     W        W  W  W     W  W  W  W        W  W  W        W        W           W     W        W  W  W  W  W  W  W     W                 W     W     W",
            "W  W  WWWW  WWWW  W  WWWW  WWWW  W  W  WWWWWWWWWW  WWWWWWWWWW  WWWW  W  W  W  W  W  W  W  WWWW  WWWWWWW  WWWW  W  WWWWWWW  WWWWWWW  W  W  W  W  W  WWWW",
            "W  W  W  W  W        W           W           W     W        W  W  W  W  W  W  W  W  W     W        W  W     W  W        W     W     W  W  W  W        W",
            "W  WWWW  W  W  WWWWWWWWWWWWWWWWWWWWWW  W  WWWWWWWWWW  W  WWWWWWW  WWWW  WWWW  WWWW  W  W  W  WWWWWWW  W  WWWWWWW  W  WWWW  WWWW  WWWW  WWWW  WWWW  W  W",
            "W  W     W     W  W  W        W  W     W     W  W     W        W  W     W  W     W  W  W  W  W           W     W  W     W  W  W     W  W  W  W  W  W  W",
            "W  W  WWWW  W  W  W  WWWW  W  W  W  WWWW  WWWW  W  W  W  WWWWWWW  WWWW  W  WWWW  WWWWWWW  WWWWWWWWWW  WWWWWWW  W  W  WWWWWWW  W  W  W  W  WWWW  W  WWWW",
            "W        W  W              W  W     W     W        W  W        W           W              W              W        W              W  W                 W",
            "WWWWWWW  W  WWWW  WWWW  WWWW  WWWW  WWWW  W  WWWWWWW  WWWW  W  WWWWWWW  WWWWWWWWWWWWWWWWWWW  W  W  W  WWWW  WWWWWWWWWW  WWWWWWW  WWWWWWW  WWWWWWW  WWWW",
            "W              W     W     W  W        W  W  W  W  W  W  W  W  W  W  W     W     W     W     W  W  W  W  W  W  W        W     W  W        W           W",
            "W  WWWW  WWWW  WWWWWWWWWWWWW  W  W  WWWWWWW  W  W  WWWW  WWWWWWW  W  WWWW  WWWW  W  WWWW  WWWWWWWWWWWWW  WWWW  WWWWWWWWWW  W  WWWW  WWWW  WWWWWWW  WWWW",
            "W  W  W  W                 W     W  W        W           W  W           W  W  W     W     W  W  W  W  W  W              W  W     W  W     W  W  W     W",
            "WWWW  WWWWWWWWWW  WWWWWWWWWW  WWWWWWW  WWWWWWWWWWWWWWWW  W  W  WWWWWWW  W  W  WWWW  W  W  W  W  W  W  W  WWWW  WWWWWWW  W  W  W  W  WWWWWWW  W  W  W  W",
            "W  W  W              W     W           W           W     W           W  W     W     W  W        W     W        W        W  W  W                 W  W  W",
            "W  W  WWWW  WWWW  WWWW  W  W  WWWW  WWWWWWWWWW  WWWW  W  W  W  WWWWWWWWWWWWW  W  WWWWWWWWWWWWW  WWWW  W  WWWWWWWWWW  W  W  W  W  WWWWWWWWWWWWWWWWWWWWWW",
            "W  W     W  W     W  W  W  W     W     W              W     W           W     W     W  W        W           W        W  W  W  W              W        W",
            "W  W  W  W  WWWW  W  WWWW  W  W  WWWW  WWWW  WWWWWWWWWWWWWWWWWWWWWW  W  W  WWWW  WWWW  WWWWWWW  W  WWWWWWWWWW  WWWW  WWWWWWWWWW  W  W  W  WWWW  WWWWWWW",
            "W     W  W  W           W     W  W  W  W  W  W        W        W  W  W  W        W        W        W  W  W  W  W  W  W        W  W  W  W     W        W",
            "W  WWWW  W  WWWWWWWWWW  W  WWWWWWW  W  W  W  WWWW  W  WWWW  WWWW  WWWW  WWWWWWWWWWWWWWWW  WWWW  WWWW  W  W  WWWW  WWWW  W  W  WWWW  WWWWWWW  WWWW  WWWW",
            "W  W                 W  W     W        W     W  W  W        W           W  W  W                          W     W  W  W  W  W  W  W     W     W        W",
            "WWWWWWW  W  WWWW  W  WWWWWWWWWWWWWWWW  WWWW  W  WWWW  WWWW  W  WWWW  WWWW  W  WWWWWWWWWW  WWWWWWW  WWWWWWWWWW  W  W  W  W  WWWW  WWWWWWW  WWWWWWWWWW  W",
            "W  W  W  W     W  W        W  W     W  W              W  W  W  W     W        W  W     W        W     W              W  W  W           W     W        W",
            "W  W  W  W  W  W  WWWWWWW  W  WWWW  W  WWWWWWW  WWWW  W  W  WWWW  WWWW  WWWWWWW  W  WWWWWWWWWWWWW  W  W  WWWW  W  WWWWWWW  WWWWWWW  WWWWWWW  W  W  WWWW",
            "W     W  W  W  W  W        W     W              W  W  W  W     W           W        W     W  W     W     W     W  W  W        W           W     W     W",
            "W  WWWWWWW  WWWWWWWWWW  WWWW  WWWW  WWWW  W  WWWW  WWWW  WWWWWWW  W  WWWW  W  W  WWWW  WWWW  WWWWWWWWWW  WWWW  WWWW  WWWWWWW  WWWWWWW  W  W  W  WWWWWWW",
            "W                 W     W  W  W  W  W     W  W        W           W  W        W     W           W        W     W              W        W  W  W        W",
            "W  WWWW  W  WWWWWWWWWW  W  W  W  W  W  WWWW  W  WWWW  WWWW  WWWW  W  WWWW  WWWWWWWWWW  WWWWWWWWWW  W  WWWWWWWWWW  WWWW  WWWW  W  WWWWWWW  WWWWWWWWWW  W",
            "W     W  W  W        W  W        W  W  W        W  W     W  W  W  W  W                 W        W  W  W  W  W     W  W  W           W     W  W  W  W  W",
            "W  WWWWWWW  WWWW  WWWWWWWWWW  WWWWWWWWWWWWWWWWWWW  W  WWWWWWW  WWWWWWW  W  W  WWWWWWWWWWWWW  W  W  W  W  W  W  W  W  W  WWWWWWW  WWWWWWW  W  W  W  WWWW",
            "W  W     W  W     W  W                 W           W  W        W  W  W  W  W  W        W     W     W           W  W  W  W  W  W  W                    W",
            "W  WWWW  WWWW  WWWW  WWWW  W  W  WWWW  W  WWWW  WWWWWWWWWW  WWWW  W  WWWW  W  W  W  WWWWWWWWWW  W  WWWWWWWWWWWWWWWW  WWWW  W  WWWW  WWWW  WWWWWWW  W  W",
            "W  W  W        W     W     W  W  W  W     W           W  W        W        W  W  W  W     W     W  W  W                 W     W     W  W  W  W     W  W",
            "W  W  WWWW  WWWWWWW  WWWWWWW  WWWW  W  W  WWWW  W  WWWW  W  W  W  W  WWWWWWW  WWWW  WWWW  WWWWWWWWWW  WWWWWWW  W  WWWWWWWWWW  W  WWWW  WWWW  WWWW  WWWW",
            "W                 W  W              W  W     W  W  W        W  W  W  W  W           W  W  W        W     W     W                       W           W  W",
            "W  W  WWWWWWWWWWWWW  WWWW  W  W  W  WWWWWWWWWWWWWWWW  WWWW  WWWWWWWWWW  W  WWWWWWW  W  W  WWWWWWW  W  WWWWWWWWWW  W  W  W  WWWW  W  WWWWWWWWWW  WWWW  W",
            "W  W     W  W              W  W  W  W  W  W  W        W  W  W  W  W        W                    W  W     W        W  W  W  W     W     W     W        W",
            "WWWWWWW  W  WWWW  WWWWWWW  WWWWWWWWWW  W  W  WWWWWWWWWW  W  W  W  WWWW  W  W  WWWWWWW  W  WWWW  W  WWWW  W  WWWWWWWWWWWWW  W  WWWW  WWWW  WWWW  WWWWWWW",
            "W              W  W     W           W  W     W     W     W        W  W  W  W  W     W  W     W     W        W           W  W  W           W  W     W  W",
            "WWWW  WWWWWWWWWWWWW  W  W  W  WWWWWWW  W  WWWW  W  W  WWWW  WWWWWWW  W  W  WWWWWWW  W  W  WWWW  WWWWWWW  WWWWWWWWWWWWW  WWWW  WWWWWWW  W  W  WWWW  W  W",
            "W     W  W     W  W  W     W     W           W  W  W        W  W  W  W  W        W  W  W     W  W     W     W           W  W  W     W  W  W  W        W",
            "W  W  W  WWWW  W  W  W  WWWWWWW  WWWWWWW  W  W  W  WWWWWWW  W  W  W  W  WWWWWWW  W  WWWWWWW  W  W  W  WWWWWWWWWW  WWWW  W  W  W  WWWWWWW  W  WWWW  WWWW",
            "W  W  W     W  W  W  W        W  W        W     W  W     W     W  W     W     W     W     W  W  W  W              W              W  W  W  W  W        W",
            "W  W  W  W  W  W  W  WWWWWWWWWWWWWWWWWWW  W  WWWWWWW  WWWW  WWWW  W  WWWWWWW  W  WWWW  WWWWWWWWWWWWWWWWWWW  WWWWWWW  WWWWWWW  W  W  W  W  W  W  WWWW  W",
            "W  W     W     W        W  W  W     W     W  W     W              W     W  W           W        W  W     W        W  W     W  W        W     W     W  W",
            "WWWWWWWWWW  WWWWWWW  W  W  W  W  WWWW  WWWW  WWWW  WWWWWWWWWW  WWWW  WWWW  WWWW  WWWWWWW  WWWWWWW  WWWW  W  W  WWWWWWW  W  WWWWWWWWWW  WWWWWWWWWWWWWWWW",
            "W        W        W  W           W        W  W        W     W  W     W        W           W     W  W  W  W  W        W  W     W     W  W  W           W",
            "W  WWWWWWWWWWWWWWWW  W  W  WWWW  WWWWWWW  WWWW  WWWW  WWWW  W  WWWW  WWWWWWW  W  W  WWWWWWW  WWWW  W  W  WWWWWWWWWW  W  WWWWWWWWWW  W  W  W  W  WWWWWWW",
            "W     W              W  W  W        W  W  W     W           W     W     W     W  W     W        W  W     W     W  W     W     W              W  W     W",
            "W  W  W  W  WWWW  W  W  WWWWWWWWWW  W  W  WWWWWWWWWW  WWWW  W  W  W  W  WWWW  WWWW  WWWWWWW  WWWW  W  WWWWWWW  W  WWWW  W  W  WWWWWWWWWW  W  WWWW  WWWW",
            "W  W     W     W  W  W           W  W        W     W     W     W  W  W  W        W        W                 W           W  W  W           W        W  W",
            "W  WWWW  W  WWWWWWW  W  W  WWWWWWW  WWWW  W  WWWW  WWWW  W  W  WWWW  WWWW  WWWWWWWWWWWWWWWW  W  WWWW  WWWWWWW  WWWWWWW  W  WWWWWWWWWWWWW  WWWWWWW  W  W",
            "W     W  W        W  W  W        W        W     W        W  W  W     W        W  W  W        W     W     W        W           W              W  W  W  W",
            "WWWW  WWWWWWWWWW  WWWW  WWWWWWWWWWWWW  WWWWWWWWWW  WWWWWWWWWWWWWWWW  WWWWWWW  W  W  W  WWWWWWWWWW  WWWWWWW  W  WWWWWWW  WWWWWWWWWWWWW  WWWW  W  W  W  W",
            "W        W        W           W     W           W     W        W     W  W        W           W  W     W     W  W        W           W  W  W     W     W",
            "W  W  W  WWWWWWWWWW  WWWW  WWWW  W  W  WWWWWWWWWW  W  W  WWWW  WWWW  W  WWWWWWW  W  W  WWWW  W  WWWWWWWWWW  W  WWWWWWWWWW  WWWWWWWWWWWWW  W  WWWWWWW  W",
            "W  W  W  W        W  W     W  W  W        W        W     W  W              W     W  W     W  W     W     W  W  W           W        W     W     W     W",
            "WWWWWWWWWW  WWWWWWWWWWWWW  W  W  WWWW  W  W  W  W  WWWWWWW  W  WWWWWWWWWWWWW  WWWW  WWWWWWW  WWWW  W  WWWWWWW  W  W  WWWWWWWWWWWWW  WWWW  WWWWWWWWWW  W",
            "W        W                    W  W     W     W  W        W           W  W        W     W              W     W  W  W  W     W  W  W              W  W  W",
            "W  WWWW  W  WWWWWWW  WWWWWWWWWWWWW  WWWW  WWWWWWW  W  WWWWWWW  WWWW  W  W  W  W  WWWWWWW  WWWWWWWWWW  W  WWWWWWWWWW  WWWW  W  W  W  WWWWWWW  WWWW  W  W",
            "W     W     W  W     W     W     W  W           W  W  W        W           W  W  W     W        W           W  W           W        W  W        W     W",
            "W  WWWWWWWWWW  W  WWWW  WWWWWWW  WWWWWWWWWW  WWWWWWW  WWWWWWW  WWWWWWWWWW  WWWWWWW  WWWW  WWWWWWW  W  W  W  W  WWWWWWWWWW  WWWWWWW  W  W  W  W  WWWW  W",
            "W     W     W                       W           W  W     W  W  W  W     W  W     W  W  W  W        W  W  W        W  W  W     W     W  W  W  W  W     W",
            "WWWWWWWWWW  WWWWWWW  WWWW  W  WWWWWWWWWWWWWWWW  W  W  WWWW  WWWW  W  W  W  W  W  W  W  WWWWWWWWWWWWW  WWWWWWWWWW  W  W  W  W  W  W  W  W  W  WWWW  WWWW",
            "W           W        W     W  W     W  W  W  W  W                 W  W     W  W           W           W        W           W  W  W     W  W  W  W     W",
            "WWWW  WWWW  WWWWWWW  WWWWWWWWWW  W  W  W  W  W  W  WWWWWWWWWWWWW  W  W  WWWWWWW  WWWWWWW  WWWW  WWWWWWWWWW  WWWWWWW  WWWWWWWWWW  WWWWWWWWWWWWW  WWWW  W",
            "W  W     W  W  W     W        W  W  W  W  W     W     W        W  W  W        W  W           W  W  W           W        W  W  W        W     W        W",
            "W  W  W  WWWW  W  WWWWWWW  WWWW  WWWW  W  WWWWWWW  WWWWWWW  W  WWWWWWW  WWWWWWWWWW  WWWWWWWWWW  W  WWWWWWW  W  W  W  W  W  W  WWWW  WWWWWWW  WWWWWWW  W",
            "W     W  W     W     W     W  W  W     W  W  W           W  W  W     W  W              W     W  W           W     W  W        W  W     W  W           W",
            "W  WWWWWWWWWW  WWWW  W  WWWW  W  WWWW  W  W  WWWW  W  W  WWWW  W  WWWWWWW  W  W  WWWWWWW  WWWWWWWWWW  WWWWWWWWWW  WWWWWWW  WWWW  WWWW  W  WWWWWWWWWW  W",
            "W     W           W     W  W           W  W        W  W     W     W        W  W     W  W     W           W           W        W  W        W  W        W",
            "WWWW  WWWW  W  WWWW  WWWW  W  WWWWWWW  W  WWWW  W  W  W  W  W  WWWW  W  W  WWWWWWWWWW  W  WWWWWWW  W  WWWWWWWWWWWWW  WWWW  W  W  W  WWWWWWW  WWWW  WWWW",
            "W           W     W     W        W        W  W  W  W  W  W     W  W  W  W  W                    W  W        W     W     W  W        W                 W",
            "W  WWWWWWW  WWWWWWW  WWWW  WWWW  WWWWWWWWWW  W  W  WWWWWWWWWW  W  WWWWWWW  W  W  WWWW  W  W  WWWWWWW  WWWWWWW  W  WWWW  W  WWWW  W  WWWW  WWWWWWWWWW  W",
            "W  W  W     W  W     W     W  W  W        W     W  W  W     W  W  W     W     W     W  W  W  W        W     W  W  W  W  W     W  W           W        W",
            "WWWW  W  W  W  W  WWWWWWWWWW  W  W  W  WWWWWWWWWWWWW  W  W  WWWW  W  WWWWWWW  WWWWWWWWWW  WWWW  WWWWWWW  W  W  WWWW  WWWWWWW  WWWWWWWWWWWWWWWWWWWWWW  W",
            "W        W        W  W           W  W  W  W  W           W  W  W        W           W     W     W     W  W     W                 W           W  W     W",
            "W  WWWWWWWWWW  WWWW  WWWW  W  W  W  WWWW  W  WWWW  WWWWWWW  W  W  W  WWWW  WWWWWWW  WWWW  W  WWWW  WWWW  WWWWWWWWWWWWWWWW  W  WWWWWWWWWWWWW  W  WWWW  W",
            "W  W  W  W     W        W  W  W     W        W     W     W        W  W  W        W  W              W  W  W           W     W        W  W  W  W        W",
            "WWWW  W  W  W  W  WWWW  W  WWWWWWWWWWWWW  WWWW  WWWW  WWWW  WWWWWWW  W  WWWW  W  WWWWWWWWWW  W  W  W  W  WWWWWWWWWW  WWWW  W  WWWWWWW  W  W  W  WWWW  W",
            "W     W  W  W        W  W           W           W     W  W     W           W  W  W     W  W  W  W     W              W  W  W     W              W     W",
            "WWWW  W  WWWW  W  W  W  W  WWWWWWWWWWWWW  WWWW  W  WWWW  W  WWWWWWW  W  W  WWWWWWW  W  W  W  WWWWWWW  W  WWWWWWW  W  W  W  WWWWWWWWWW  WWWW  W  W  W  W",
            "W              W  W  W           W           W           W     W     W  W           W           W              W  W  W              W     W  W  W  W   ",
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW   ",
        ],
        True,
    ),
]
